"""
Write a KB entry to the shared vault.

A KB entry is a markdown file with YAML frontmatter, containing both the
LLM-generated summary AND the full scraped article body. Files land in
`<VAULT>/kb/raw/nate-substack/<slug>.md` where <slug> is the Substack
URL slug (deterministic from URL → idempotent → no separate state file).

This module also handles vault git operations at the end of a run so new
KB files reach the shared brain immediately.
"""

import os
import re
import subprocess
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse


NATE_SUBDIR = "kb/raw/nate-substack"
VAULT_PATH_ENV = "VAULT_PATH"


def get_vault_path() -> Path:
    raw = os.getenv(VAULT_PATH_ENV)
    if not raw:
        raise EnvironmentError(f"{VAULT_PATH_ENV} not set in environment")
    path = Path(raw).expanduser().resolve()
    if not path.is_dir():
        raise FileNotFoundError(f"VAULT_PATH does not exist: {path}")
    if not (path / ".git").is_dir():
        raise FileNotFoundError(f"VAULT_PATH is not a git repo: {path}")
    return path


def slug_from_url(url: str) -> str:
    path = urlparse(url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) < 2 or parts[0] != "p":
        raise ValueError(f"URL does not look like a Substack article: {url}")
    return parts[1]


def kb_entry_path(url: str, vault_path: Path | None = None) -> Path:
    vault = vault_path or get_vault_path()
    return vault / NATE_SUBDIR / f"{slug_from_url(url)}.md"


def already_in_vault(url: str, vault_path: Path | None = None) -> bool:
    return kb_entry_path(url, vault_path).exists()


def _render_frontmatter(fm: dict) -> str:
    lines = ["---"]
    for k, v in fm.items():
        if isinstance(v, list):
            if v:
                lines.append(f"{k}: [{', '.join(str(x) for x in v)}]")
            else:
                lines.append(f"{k}: []")
        elif v == "" or v is None:
            lines.append(f"{k}:")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines)


def build_kb_markdown(summary: dict, full_text: str) -> str:
    """
    Compose the markdown content for a KB entry from a summary dict + the
    full scraped article body. Pure function — no I/O.
    """
    slug = slug_from_url(summary["url"])
    fetched = datetime.now().strftime("%Y-%m-%d")
    published = summary.get("published_date") or ""
    tldr = (summary.get("tldr") or "").strip()
    title = summary.get("title") or slug.replace("-", " ").title()

    first_sentence = re.split(r"(?<=[.!?])\s+", tldr, maxsplit=1)[0] if tldr else ""
    description = f"{title} — {first_sentence}" if first_sentence else title

    fm = {
        "name": slug,
        "description": description[:200],
        "type": "kb-raw",
        "source": summary["url"],
        "publication": "Nate's Newsletter (Substack)",
        "author": "Nate",
        "published": published,
        "fetched": fetched,
        "tags": summary.get("tags") or [],
    }
    if summary.get("youtube_url"):
        fm["youtube_url"] = summary["youtube_url"]

    fm_block = _render_frontmatter(fm)

    body = [f"# {title}", "", f"**Source:** {summary['url']}", "**Author:** Nate"]
    if published:
        body.append(f"**Published:** {published}")
    body += ["", "## TL;DR", "", tldr or "_No TL;DR generated._", ""]

    takeaways = summary.get("key_takeaways") or []
    if takeaways:
        body += ["## Key Takeaways", ""]
        for t in takeaways:
            body.append(f"- {t}")
        body.append("")

    why = (summary.get("why_it_matters") or "").strip()
    if why:
        body += ["## Why It Matters", "", why, ""]

    tags = summary.get("tags") or []
    if tags:
        body += ["## Tags", "", ", ".join(tags), ""]

    body += ["---", "", "## Full article", "", full_text.strip(), ""]
    body += [
        "---",
        "",
        f"*Summary auto-generated by nate-substack-kb-digest. Original at {summary['url']}.*",
        "",
    ]

    return f"{fm_block}\n\n" + "\n".join(body)


def write_kb_entry(
    summary: dict, full_text: str, vault_path: Path | None = None
) -> Path:
    """
    Atomically write the KB entry to disk. Returns the path written.
    Caller is responsible for git ops (use `run_vault_git_ops` once after batch).
    """
    vault = vault_path or get_vault_path()
    target = vault / NATE_SUBDIR / f"{slug_from_url(summary['url'])}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    content = build_kb_markdown(summary, full_text)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(target)
    return target


def run_vault_git_ops(vault_path: Path, commit_message: str, log) -> None:
    """
    Pull (rebase), stage NATE_SUBDIR, commit if changes, push.
    Logs at info level. Silent no-op if nothing staged.
    """
    try:
        subprocess.run(
            ["git", "pull", "--rebase"],
            cwd=vault_path,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        log.warning(
            f"Vault: git pull --rebase failed (continuing): {exc.stderr.strip()}"
        )

    subprocess.run(
        ["git", "add", NATE_SUBDIR],
        cwd=vault_path,
        check=True,
        capture_output=True,
        text=True,
    )

    status = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=vault_path,
        capture_output=True,
    )
    if status.returncode == 0:
        log.info("Vault: nothing to commit.")
        return

    subprocess.run(
        [
            "git",
            "-c", "user.name=Joe Fisher",
            "-c", "user.email=joefisherpersonal@gmail.com",
            "commit",
            "-m", commit_message,
        ],
        cwd=vault_path,
        check=True,
        capture_output=True,
        text=True,
    )

    subprocess.run(
        ["git", "push"],
        cwd=vault_path,
        check=True,
        capture_output=True,
        text=True,
    )
    log.info("Vault: pushed.")
